package org.wicketstuff.springboot.starter.example;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.TestRestTemplate;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureTestRestTemplate;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Guards the contract that {@code wicketstuff-spring-boot-starter} is the only dependency an
 * application needs.
 * <p>
 * This module deliberately declares nothing but the starter at compile scope, so the embedded
 * servlet container exercised here can only have arrived transitively from the starter itself.
 * Without that, a project generated by Spring Initializr with just "Wicket" selected boots as a
 * plain non-web application and silently serves nothing.
 * </p>
 * <p>
 * A {@code bannedDependencies} enforcer rule in this module's pom keeps that precondition true:
 * declaring a Spring Boot starter here at compile scope would make this test pass without the
 * starter supplying anything.
 * </p>
 * <p>
 * The filter name is overridden because Wicket keys its application registry by it, so two tests
 * that each start a real container in the same JVM collide on the default name.
 * </p>
 */
@SpringBootTest(
		webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
		properties = "wicket.filter-name=self-sufficiency-filter")
@AutoConfigureTestRestTemplate
class StarterSelfSufficiencyTest {

	@Autowired
	private ApplicationContext context;

	@Autowired
	private TestRestTemplate restTemplate;

	/**
	 * Asserted on the class name rather than the type so that this class does not itself need a
	 * servlet-only import, which would make it fail to compile rather than fail as a test.
	 */
	@Test
	void theStarterAloneBootsAServletWebApplication() {
		assertThat(context.getClass().getName()).endsWith("ServletWebServerApplicationContext");
	}

	@Test
	void theStarterAloneServesTheDefaultHomePage() {
		ResponseEntity<String> response = restTemplate.getForEntity("/", String.class);

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
		assertThat(response.getBody()).contains("Wicket Spring Boot Starter");
	}
}
