/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.wicketstuff.kendo.ui;

import org.wicketstuff.kendo.ui.form.button.Button;

/**
 * Provides default Kendo UI icons. Might be used to decorate a {@link Button} for instance.
 *
 * @author Sebastien Briquet - sebfz1
 * @see <a href=
 *      "http://docs.telerik.com/kendo-ui/styles-and-layout/icons-web">http://docs.telerik.com/kendo-ui/styles-and-layout/icons-web</a>
 *
 */
public class KendoIcon
{
    /** css class mastering icon display */
    public static final String K_ICON = "k-icon k-font-icon";

    public static final String NONE = "";

    // Actions //
    public static final String ACCESSIBILITY = "accessibility";
    public static final String ARROW_ROTATE_CCW = "arrow-rotate-ccw";
    public static final String ARROW_ROTATE_CCW_SMALL = "arrow-rotate-ccw-small";
    public static final String ARROW_ROTATE_CW = "arrow-rotate-cw";
    public static final String ARROW_ROTATE_CW_SMALL = "arrow-rotate-cw-small";
    public static final String ARROWS_MOVE = "arrows-move";
    public static final String ARROWS_NO_REPEAT = "arrows-no-repeat";
    public static final String BARCODE = "barcode";
    public static final String BARCODE_OUTLINE = "barcode-outline";
    public static final String BARCODE_QR_CODE_SCANNER = "barcode-qr-code-scanner";
    public static final String BARCODE_SCANNER = "barcode-scanner";
    public static final String CALCULATOR = "calculator";
    public static final String CALENDAR = "calendar";
    public static final String CANCEL = "cancel";
    public static final String CANCEL_CIRCLE = "cancel-circle";
    public static final String CANCEL_OUTLINE = "cancel-outline";
    public static final String CART = "cart";
    public static final String CHECK = "check";
    public static final String CHECK_CIRCLE = "check-circle";
    public static final String CHECK_OUTLINE = "check-outline";
    public static final String CLOCK = "clock";
    public static final String CLOCK_ARROW_ROTATE = "clock-arrow-rotate";
    public static final String CONNECTOR = "connector";
    public static final String DIVIDE = "divide";
    public static final String DOWNLOAD = "download";
    public static final String DOWNLOAD_LIGHT = "download-light";
    public static final String EQUAL = "equal";
    public static final String EXPORT = "export";
    public static final String EYE = "eye";
    public static final String EYE_SLASH = "eye-slash";
    public static final String FILTER = "filter";
    public static final String FILTER_ADD_EXPRESSION = "filter-add-expression";
    public static final String FILTER_ADD_GROUP = "filter-add-group";
    public static final String FILTER_CLEAR = "filter-clear";
    public static final String FILTER_SMALL = "filter-small";
    public static final String FILTER_SORT_ASC_SMALL = "filter-sort-asc-small";
    public static final String FILTER_SORT_DESC_SMALL = "filter-sort-desc-small";
    public static final String GEAR = "gear";
    public static final String GEARS = "gears";
    public static final String GREATER_OR_EQUAL = "greater-or-equal";
    public static final String HAND = "hand";
    public static final String HYPERLINK_OPEN = "hyperlink-open";
    public static final String HYPERLINK_OPEN_SM = "hyperlink-open-sm";
    public static final String IMPORT = "import";
    public static final String KPI_STATUS_DENY = "kpi-status-deny";
    public static final String KPI_STATUS_HOLD = "kpi-status-hold";
    public static final String KPI_STATUS_OPEN = "kpi-status-open";
    public static final String LAUNCH = "launch";
    public static final String LESS_OR_EQUAL = "less-or-equal";
    public static final String LINK = "link";
    public static final String LINK_VERTICAL = "link-vertical";
    public static final String LOCK = "lock";
    public static final String LOGIN = "login";
    public static final String LOGOUT = "logout";
    public static final String MINUS = "minus";
    public static final String MINUS_CIRCLE = "minus-circle";
    public static final String MINUS_OUTLINE = "minus-outline";
    public static final String MINUS_SM = "minus-sm";
    public static final String NON_RECURRENCE = "non-recurrence";
    public static final String NOT_EQUAL = "not-equal";
    public static final String OPTIMIZATION = "optimization";
    public static final String PAPER_PLANE = "paper-plane";
    public static final String PAPERCLIP = "paperclip";
    public static final String PAPERCLIP_ALT = "paperclip-alt";
    public static final String PENCIL = "pencil";
    public static final String PLUS = "plus";
    public static final String PLUS_CIRCLE = "plus-circle";
    public static final String PLUS_OUTLINE = "plus-outline";
    public static final String PLUS_SM = "plus-sm";
    public static final String POINTER = "pointer";
    public static final String PRINT = "print";
    public static final String QR_CODE = "qr-code";
    public static final String QR_CODE_OUTLINE = "qr-code-outline";
    public static final String QR_CODE_SCANNER = "qr-code-scanner";
    public static final String REDO = "redo";
    public static final String SAVE = "save";
    public static final String SCALE = "scale";
    public static final String SEARCH = "search";
    public static final String SECURITY_CHECK_OUTLINE = "security-check-outline";
    public static final String SECURITY_CHECK_SOLID = "security-check-solid";
    public static final String SECURITY_LOCK_OUTLINE = "security-lock-outline";
    public static final String SECURITY_LOCK_SOLID = "security-lock-solid";
    public static final String SET_COLUMN_POSITION = "set-column-position";
    public static final String SIGNATURE = "signature";
    public static final String SORT_ASC = "sort-asc";
    public static final String SORT_ASC_SMALL = "sort-asc-small";
    public static final String SORT_CLEAR = "sort-clear";
    public static final String SORT_DESC = "sort-desc";
    public static final String SORT_DESC_SMALL = "sort-desc-small";
    public static final String STICK = "stick";
    public static final String TRASH = "trash";
    public static final String UNDO = "undo";
    public static final String UNLINK = "unlink";
    public static final String UNLINK_VERTICAL = "unlink-vertical";
    public static final String UNLOCK = "unlock";
    public static final String UNSTICK = "unstick";
    public static final String UPGRADE_OUTLINE = "upgrade-outline";
    public static final String UPGRADE_RELOAD = "upgrade-reload";
    public static final String UPGRADE_SOLID = "upgrade-solid";
    public static final String UPLOAD = "upload";
    public static final String WINDOW = "window";
    public static final String WINDOW_MINIMIZE = "window-minimize";
    public static final String WINDOW_RESTORE = "window-restore";
    public static final String WRENCH = "wrench";
    public static final String X = "x";
    public static final String X_CIRCLE = "x-circle";
    public static final String X_OUTLINE = "x-outline";
    public static final String ZOOM_IN = "zoom-in";
    public static final String ZOOM_OUT = "zoom-out";
    public static final @Deprecated String ATTACHMENT = "attachment";
    public static final @Deprecated String ATTACHMENT_45 = "attachment-45";
    public static final @Deprecated String CHECKMARK = "checkmark";
    public static final @Deprecated String CHECKMARK_CIRCLE = "checkmark-circle";
    public static final @Deprecated String CHECKMARK_OUTLINE = "checkmark-outline";
    public static final @Deprecated String CLIP = "clip";
    public static final @Deprecated String CLIP_45 = "clip-45";
    public static final @Deprecated String CLOSE = "close";
    public static final @Deprecated String CLOSE_CIRCLE = "close-circle";
    public static final @Deprecated String CLOSE_OUTLINE = "close-outline";
    public static final @Deprecated String COG = GEAR;
    public static final @Deprecated String COGS = GEARS;
    public static final @Deprecated String CUSTOM = "custom";
    public static final @Deprecated String DELETE = "delete";
    public static final @Deprecated String EDIT = "edit";
    public static final @Deprecated String FILTER_SM = "filter-sm";
    public static final @Deprecated String FILTER_SORT_ASC_SM = FILTER_SORT_ASC_SMALL;
    public static final @Deprecated String FILTER_SORT_DESC_SM = FILTER_SORT_DESC_SMALL;
    public static final @Deprecated String FLOPPY = "floppy";
    public static final @Deprecated String HYPERLINK = "hyperlink";
    public static final @Deprecated String HYPERLINK_REMOVE = "hyperlink-remove";
    public static final @Deprecated String LINK_HORIZONTAL = "link-horizontal";
    public static final @Deprecated String MOVE = "move";
    public static final @Deprecated String PAN = "pan";
    public static final @Deprecated String PREVIEW = "preview";
    public static final @Deprecated String PRINTER = PRINT;
    public static final @Deprecated String REFRESH = "refresh";
    public static final @Deprecated String REFRESH_SM = "refresh-sm";
    public static final @Deprecated String RELOAD = UPGRADE_RELOAD;
    public static final @Deprecated String RELOAD_SM = UPGRADE_RELOAD;
    public static final @Deprecated String RESET = "reset";
    public static final @Deprecated String RESET_SM = "reset-sm";
    public static final @Deprecated String SETTINGS = WRENCH;
    public static final @Deprecated String SHOPPING_CART = CART;
    public static final @Deprecated String SORT_ASC_SM = SORT_ASC_SMALL;
    public static final @Deprecated String SORT_DESC_SM = SORT_DESC_SMALL;
    public static final @Deprecated String TILES = "tiles";
    public static final @Deprecated String UNLINK_HORIZONTAL = "unlink-horizontal";
    public static final @Deprecated String UNSORT = "unsort";
    public static final @Deprecated String WINDOW_MAXIMIZE = "window-maximize";
    public static final @Deprecated String WINDOWS = "windows";
    public static final @Deprecated String ZOOM = ZOOM_IN;

    // Alerts //
    // Part of Notifications

    // Arrows //
    public static final String ARROW_DOWN = "arrow-down";
    public static final String ARROW_DOWN_LEFT = "arrow-down-left";
    public static final String ARROW_LEFT = "arrow-left";
    public static final String ARROW_RIGHT = "arrow-right";
    public static final String ARROW_UP = "arrow-up";
    public static final String ARROWS_AXES = "arrows-axes";
    public static final String ARROWS_LEFT_RIGHT = "arrows-left-right";
    public static final String ARROWS_SWAP = "arrows-swap";
    public static final String ARROWS_TOP_BOTTOM = "arrows-top-bottom";
    public static final String BORDER_RADIUS_BOTTOM_LEFT = "border-radius-bottom-left";
    public static final String BORDER_RADIUS_BOTTOM_RIGHT = "border-radius-bottom-right";
    public static final String BORDER_RADIUS_TOP_LEFT = "border-radius-top-left";
    public static final String BORDER_RADIUS_TOP_RIGHT = "border-radius-top-right";
    public static final String BORDER_RADIUS = "border-radius";
    public static final String BORDER_STYLE_BOTTOM = "border-style-bottom";
    public static final String BORDER_STYLE_LEFT = "border-style-left";
    public static final String BORDER_STYLE_RIGHT = "border-style-right";
    public static final String BORDER_STYLE_TOP = "border-style-top";
    public static final String BORDER_STYLE = "border-style";
    public static final String BORDER_COLOR = "border-color";
    public static final String BORDER_TYPE = "border-type";

    // Charts //
    public static final String GAUGE_LINEAR = "gauge-linear";
    public static final String GAUGE_RADIAL = "gauge-radial";
    public static final String GRAPH = "graph";
    public static final String CHART_COLUMN_CLUSTERED = "chart-column-clustered";
    public static final String CHART_COLUMN_STACKED = "chart-column-stacked";
    public static final String CHART_COLUMN_STACKED100 = "chart-column-stacked100";
    public static final String CHART_COLUMN_RANGE = "chart-column-range";
    public static final String CHART_BAR_CLUSTERED = "chart-bar-clustered";
    public static final String CHART_BAR_STACKED = "chart-bar-stacked";
    public static final String CHART_BAR_STACKED100 = "chart-bar-stacked100";
    public static final String CHART_BAR_RANGE = "chart-bar-range";
    public static final String CHART_AREA_CLUSTERED = "chart-area-clustered";
    public static final String CHART_AREA_STACKED = "chart-area-stacked";
    public static final String CHART_AREA_STACKED100 = "chart-area-stacked100";
    public static final String CHART_AREA_RANGE = "chart-area-range";
    public static final String CHART_LINE = "chart-line";
    public static final String CHART_LINE_STACKED = "chart-line-stacked";
    public static final String CHART_LINE_STACKED100 = "chart-line-stacked100";
    public static final String CHART_LINE_MARKERS = "chart-line-markers";
    public static final String CHART_LINE_STACKED_MARKERS = "chart-line-stacked-markers";
    public static final String CHART_LINE_STACKED100_MARKERS = "chart-line-stacked100-markers";
    public static final String CHART_PIE = "chart-pie";
    public static final String CHART_DOUGHNUT = "chart-doughnut";
    public static final String CHART_SCATTER = "chart-scatter";
    public static final String CHART_SCATTER_SMOOTH_LINES_MARKERS = "chart-scatter-smooth-lines-markers";
    public static final String CHART_SCATTER_SMOOTH_LINES = "chart-scatter-smooth-lines";
    public static final String CHART_SCATTER_STRAIGHT_LINES_MARKERS = "chart-scatter-straight-lines-markers";
    public static final String CHART_SCATTER_STRAIGHT_LINES = "chart-scatter-straight-lines";
    public static final String CHART_BUBBLE = "chart-bubble";
    public static final String CHART_CANDLESTICK = "chart-candlestick";
    public static final String CHART_OHLC = "chart-ohlc";
    public static final String CHART_RADAR = "chart-radar";
    public static final String CHART_RADAR_MARKERS = "chart-radar-markers";
    public static final String CHART_RADAR_FILLED = "chart-radar-filled";
    public static final String CHART_ROSE = "chart-rose";
    public static final String CHART_CHOROPLETH = "chart-choropleth";

    // CSS //
    // This section seems to be an intersection of other sections like Borders, List and parts of
    // Layout

    // Editing //
    public static final String ALIGN_ITEMS_BASELINE = "align-items-baseline";
    public static final String ALIGN_ITEMS_BASELINE_ALT = "align-items-baseline-alt";
    public static final String ALIGN_ITEMS_CENTER = "align-items-center";
    public static final String ALIGN_ITEMS_CENTER_ALT = "align-items-center-alt";
    public static final String ALIGN_ITEMS_END = "align-items-end";
    public static final String ALIGN_ITEMS_END_ALT = "align-items-end-alt";
    public static final String ALIGN_ITEMS_START = "align-items-start";
    public static final String ALIGN_ITEMS_START_ALT = "align-items-start-alt";
    public static final String ALIGN_ITEMS_STRETCH = "align-items-stretch";
    public static final String ALIGN_ITEMS_STRETCH_ALT = "align-items-stretch-alt";
    public static final String ALIGN_SELF_CENTER = "align-self-center";
    public static final String ALIGN_SELF_CENTER_ALT = "align-self-center-alt";
    public static final String ALIGN_SELF_END = "align-self-end";
    public static final String ALIGN_SELF_END_ALT = "align-self-end-alt";
    public static final String ALIGN_SELF_START = "align-self-start";
    public static final String ALIGN_SELF_START_ALT = "align-self-start-alt";
    public static final String ALIGN_SELF_STRETCH = "align-self-stretch";
    public static final String ALIGN_SELF_STRETCH_ALT = "align-self-stretch-alt";
    public static final String ALIGN_TO_GRID = "align-to-grid";
    public static final String ANCHOR = "anchor";
    public static final String APPLY_FORMAT = "apply-format";
    public static final String AREA = "area";
    public static final String ARROW_SHAPE = "arrow-shape";
    public static final String BINOCULARS = "binoculars";
    public static final String BOOK = "book";
    public static final String BORDER_RADIUS_UNDEFINED = "border-radius-undefined";
    public static final String BORDER_WIDTH = "border-width";
    public static final String BRING_BACKWARD = "bring-backward";
    public static final String BRING_FORWARD = "bring-forward";
    public static final String BRING_TO_BACK = "bring-to-back";
    public static final String BRING_TO_FRONT = "bring-to-front";
    public static final String BUILDING_BLOCKS = "building-blocks";
    public static final String BUTTON = "button";
    public static final String CALENDAR_DATE = "calendar-date";
    public static final String CELL_SPLIT_HORIZONTALLY = "cell-split-horizontally";
    public static final String CELL_SPLIT_VERTICALLY = "cell-split-vertically";
    public static final String CELLS_MERGE = "cells-merge";
    public static final String CELLS_MERGE_HORIZONTALLY = "cells-merge-horizontally";
    public static final String CELLS_MERGE_VERTICALLY = "cells-merge-vertically";
    public static final String CHANGE_MANUALLY = "change-manually";
    public static final String CIRCLE_SHAPE = "circle-shape";
    public static final String CLEAR_CSS = "clear-css";
    public static final String CLIPBOARD = "clipboard";
    public static final String CLIPBOARD_CODE = "clipboard-code";
    public static final String CLIPBOARD_HTML = "clipboard-html";
    public static final String CLIPBOARD_MARKDOWN = "clipboard-markdown";
    public static final String CLIPBOARD_TEXT = "clipboard-text";
    public static final String CLIPBOARD_WORD = "clipboard-word";
    public static final String CLIPBOARD_WORD_ALT = "clipboard-word-alt";
    public static final String CODE_SNIPPET = "code-snippet";
    public static final String COLUMN_FREEZE = "column-freeze";
    public static final String COMBOBOX = "combobox";
    public static final String COMMENT = "comment";
    public static final String COMMENT_REMOVE = "comment-remove";
    public static final String COMMENTS_REMOVE = "comments-remove";
    public static final String COPY = "copy";
    public static final String COPY_FORMAT = "copy-format";
    public static final String CROSSTAB = "crosstab";
    public static final String CROSSTAB_WIZARD = "crosstab-wizard";
    public static final String CUBE = "cube";
    public static final String CUSTOM_FORMAT = "custom-format";
    public static final String CUSTOM_ICON = "custom-icon";
    public static final String CUT = "cut";
    public static final String DECIMAL_DECREASE = "decimal-decrease";
    public static final String DECIMAL_INCREASE = "decimal-increase";
    public static final String DECREASE_HORIZONTAL_SPACING = "decrease-horizontal-spacing";
    public static final String DECREASE_VERTICAL_SPACING = "decrease-vertical-spacing";
    public static final String DIMENSIONS = "dimensions";
    public static final String DISTANCE = "distance";
    public static final String DOCUMENT_MANAGER = "document-manager";
    public static final String DOLLAR = "dollar";
    public static final String DRAW_FREE = "draw-free";
    public static final String DROPDOWN = "dropdown";
    public static final String DROPLET_SLASH = "droplet-slash";
    public static final String EDIT_ANNOTATIONS = "edit-annotations";
    public static final String EDIT_TOOLS = "edit-tools";
    public static final String ENVELOP_LINK = "envelop-link";
    public static final String ENVELOPE_LINK = "envelope-link";
    public static final String ERASER_OUTLINE = "eraser-outline";
    public static final String ERASER_SOLID = "eraser-solid";
    public static final String EYEDROPPER = "eyedropper";
    public static final String FILE_WRENCH = "file-wrench";
    public static final String FLASH_MANAGER = "flash-manager";
    public static final String FORM = "form";
    public static final String FORM_ELEMENT = "form-element";
    public static final String FORMAT_CODE_BLOCK = "format-code-block";
    public static final String FORMULA_FX = "formula-fx";
    public static final String FREE_TEXT = "free-text";
    public static final String GLOBE_LINK = "globe-link";
    public static final String GLOBE_UNLINK = "globe-unlink";
    public static final String GROUP_BOX = "group-box";
    public static final String HANDLE_RESIZE = "handle-resize";
    public static final String HANDLE_RESIZE_ALT = "handle-resize-alt";
    public static final String HEXAGON_SHAPE = "hexagon-shape";
    public static final String HIGHLIGHT = "highlight";
    public static final String HIGHLIGHT_FREE = "highlight-free";
    public static final String IMAGE_ABSOLUTE_POSITION = "image-absolute-position";
    public static final String IMAGE_ADD = "image-add";
    public static final String IMAGE_EDIT = "image-edit";
    public static final String IMAGE_MAP_EDITOR = "image-map-editor";
    public static final String INCREASE_HORIZONTAL_SPACING = "increase-horizontal-spacing";
    public static final String INCREASE_VERTICAL_SPACING = "increase-vertical-spacing";
    public static final String INPUTBOX = "inputbox";
    public static final String INSERT_FREE_TEXT = "insert-free-text";
    public static final String JUSTIFY_CONTENT_AROUND = "justify-content-around";
    public static final String JUSTIFY_CONTENT_AROUND_ALT = "justify-content-around-alt";
    public static final String JUSTIFY_CONTENT_BETWEEN = "justify-content-between";
    public static final String JUSTIFY_CONTENT_BETWEEN_ALT = "justify-content-between-alt";
    public static final String JUSTIFY_CONTENT_CENTER = "justify-content-center";
    public static final String JUSTIFY_CONTENT_CENTER_ALT = "justify-content-center-alt";
    public static final String JUSTIFY_CONTENT_END = "justify-content-end";
    public static final String JUSTIFY_CONTENT_END_ALT = "justify-content-end-alt";
    public static final String JUSTIFY_CONTENT_START = "justify-content-start";
    public static final String JUSTIFY_CONTENT_START_ALT = "justify-content-start-alt";
    public static final String LINE_SHAPE = "line-shape";
    public static final String LINK_ADD = "link-add";
    public static final String MAKE_HORIZONTAL_SPACING_EQUAL = "make-horizontal-spacing-equal";
    public static final String MAKE_SAME_HEIGHT = "make-same-height";
    public static final String MAKE_SAME_SIZE = "make-same-size";
    public static final String MAKE_SAME_WIDTH = "make-same-width";
    public static final String MAKE_VERTICAL_SPACING_EQUAL = "make-vertical-spacing-equal";
    public static final String PANE_FREEZE = "pane-freeze";
    public static final String PARAGRAPH_ADD = "paragraph-add";
    public static final String PARAGRAPH_MARK = "paragraph-mark";
    public static final String PASSWORD = "password";
    public static final String PASSWORD_BOX = "password-box";
    public static final String PERCENT = "percent";
    public static final String PERIMETER = "perimeter";
    public static final String PUZZLE_PIECE = "puzzle-piece";
    public static final String RECTANGLE_SHAPE = "rectangle-shape";
    public static final String REMOVE_HORIZONTAL_SPACING = "remove-horizontal-spacing";
    public static final String REMOVE_VERTICAL_SPACING = "remove-vertical-spacing";
    public static final String REPLACE_FREE_TEXT = "replace-free-text";
    public static final String ROW_COLLAPSE = "row-collapse";
    public static final String ROW_EXPAND = "row-expand";
    public static final String ROW_FREEZE = "row-freeze";
    public static final String RULER_OUTLINE = "ruler-outline";
    public static final String RULER_OUTLINE_ALT = "ruler-outline-alt";
    public static final String RULER_SOLID = "ruler-solid";
    public static final String RULER_SOLID_ALT = "ruler-solid-alt";
    public static final String RULER_TRIANGLE_OUTLINE = "ruler-triangle-outline";
    public static final String RULER_TRIANGLE_SOLID = "ruler-triangle-solid";
    public static final String SELECT_ALL = "select-all";
    public static final String SELECT_BOX = "select-box";
    public static final String SILVERLIGHT = "silverlight";
    public static final String SIZE_TO_GRID = "size-to-grid";
    public static final String SNAP_GRID = "snap-grid";
    public static final String SNAP_TO_GRIDLINES = "snap-to-gridlines";
    public static final String SNAP_TO_SNAPLINES = "snap-to-snaplines";
    public static final String SPELL_CHECKER = "spell-checker";
    public static final String STAMP = "stamp";
    public static final String STICKY_NOTE = "sticky-note";
    public static final String STRIP_ALL_FORMATTING = "strip-all-formatting";
    public static final String STRIP_CSS_FORMAT = "strip-css-format";
    public static final String STRIP_FONT_ELEMENTS = "strip-font-elements";
    public static final String STRIP_SPAN_ELEMENTS = "strip-span-elements";
    public static final String STRIP_WORD_FORMATTING = "strip-word-formatting";
    public static final String SUM = "sum";
    public static final String SYMBOL = "symbol";
    public static final String TABLE = "table";
    public static final String TABLE_ADD = "table-add";
    public static final String TABLE_BODY = "table-body";
    public static final String TABLE_CELL = "table-cell";
    public static final String TABLE_CELL_DELETE = "table-cell-delete";
    public static final String TABLE_CELL_PROPERTIES = "table-cell-properties";
    public static final String TABLE_COLUMN_DELETE = "table-column-delete";
    public static final String TABLE_COLUMN_GROUPS = "table-column-groups";
    public static final String TABLE_COLUMN_INSERT_LEFT = "table-column-insert-left";
    public static final String TABLE_COLUMN_INSERT_RIGHT = "table-column-insert-right";
    public static final String TABLE_CORNER = "table-corner";
    public static final String TABLE_DELETE = "table-delete";
    public static final String TABLE_PROPERTIES = "table-properties";
    public static final String TABLE_ROW_DELETE = "table-row-delete";
    public static final String TABLE_ROW_GROUPS = "table-row-groups";
    public static final String TABLE_ROW_INSERT_ABOVE = "table-row-insert-above";
    public static final String TABLE_ROW_INSERT_BELOW = "table-row-insert-below";
    public static final String TABLE_UNMERGE = "table-unmerge";
    public static final String TABLE_WIZARD = "table-wizard";
    public static final String TEMPLATE_MANAGER = "template-manager";
    public static final String TEXTAREA = "textarea";
    public static final String TEXTBOX = "textbox";
    public static final String TEXTBOX_HIDDEN = "textbox-hidden";
    public static final String THUMBNAILS_DOWN = "thumbnails-down";
    public static final String THUMBNAILS_LEFT = "thumbnails-left";
    public static final String THUMBNAILS_RIGHT = "thumbnails-right";
    public static final String THUMBNAILS_UP = "thumbnails-up";
    public static final String TOGGLE_FULL_SCREEN_MODE = "toggle-full-screen-mode";
    public static final String TOOLBAR_FLOAT = "toolbar-float";
    public static final String TRACK_CHANGES = "track-changes";
    public static final String TRACK_CHANGES_ACCEPT = "track-changes-accept";
    public static final String TRACK_CHANGES_ACCEPT_ALL = "track-changes-accept-all";
    public static final String TRACK_CHANGES_ENABLE = "track-changes-enable";
    public static final String TRACK_CHANGES_REJECT = "track-changes-reject";
    public static final String TRACK_CHANGES_REJECT_ALL = "track-changes-reject-all";
    public static final String VALIDATION_DATA = "validation-data";
    public static final String VALIDATION_XHTML = "validation-xhtml";
    public static final @Deprecated String DICTIONARY_ADD = "dictionary-add";
    public static final @Deprecated String FILES = "files";
    public static final @Deprecated String FIND = "find";
    public static final @Deprecated String FIND_AND_REPLACE = "find-and-replace";
    public static final @Deprecated String HYPERLINK_EMAIL = "hyperlink-email";
    public static final @Deprecated String HYPERLINK_GLOBE = "hyperlink-globe";
    public static final @Deprecated String HYPERLINK_GLOBE_REMOVE = "hyperlink-globe-remove";
    public static final @Deprecated String HYPERLINK_INSERT = "hyperlink-insert";
    public static final @Deprecated String HYPERLINK_LIGHT_DIALOG = "hyperlink-light-dialog";
    public static final @Deprecated String IMAGE_INSERT = "image-insert";
    public static final @Deprecated String IMAGE_LIGHT_DIALOG = "image-light-dialog";
    public static final @Deprecated String INDENT_DECREASE = "indent-decrease";
    public static final @Deprecated String INDENT_INCREASE = "indent-increase";
    public static final @Deprecated String INSERT_DOWN = "insert-down";
    public static final @Deprecated String INSERT_UP = "insert-up";
    public static final @Deprecated String LIST_BULLETED = "list-bulleted";
    public static final @Deprecated String LIST_NUMBERED = "list-numbered";
    public static final @Deprecated String MODULE_MANAGER = "module-manager";
    public static final @Deprecated String PAGE_PROPERTIES = "page-properties";
    public static final @Deprecated String PASTE = "paste";
    public static final @Deprecated String PASTE_AS_HTML = "paste-as-html";
    public static final @Deprecated String PASTE_FROM_WORD = "paste-from-word";
    public static final @Deprecated String PASTE_FROM_WORD_STRIP_FILE = "paste-from-word-strip-file";
    public static final @Deprecated String PASTE_HTML = "paste-html";
    public static final @Deprecated String PASTE_MARKDOWN = "paste-markdown";
    public static final @Deprecated String PASTE_PLAIN_TEXT = "paste-plain-text";
    public static final @Deprecated String RULE_HORIZONTAL = "rule-horizontal";
    public static final @Deprecated String STRIP_ALL_FORMATING = "strip-all-formating";
    public static final @Deprecated String STYLE_BUILDER = "style-builder";
    public static final @Deprecated String TABLE_LIGHT_DIALOG = "table-light-dialog";
    public static final @Deprecated String VIDEO_EXTERNAL = "video-external";

    // Files and Folders //
    public static final String AGGREGATE_FIELDS = "aggregate-fields";
    public static final String CLOUD = "cloud";
    public static final String CODE = "code";
    public static final String CS = "cs";
    public static final String CSPROJ = "csproj";
    public static final String CSS = "css";
    public static final String CSS3 = "css3";
    public static final String DATA = "data";
    public static final String DATA_CSV = "data-csv";
    public static final String DATA_JSON = "data-json";
    public static final String DATA_ODS = "data-ods";
    public static final String DATA_REST = "data-rest";
    public static final String DATA_SDS = "data-sds";
    public static final String DATA_SQL = "data-sql";
    public static final String DATA_WEB = "data-web";
    public static final String DETAIL_SECTION = "detail-section";
    public static final String EXE = "exe";
    public static final String FILE = "file";
    public static final String FILE_ADD = "file-add";
    public static final String FILE_ASCX = "file-ascx";
    public static final String FILE_AUDIO = "file-audio";
    public static final String FILE_BAC = "file-bac";
    public static final String FILE_CONFIG = "file-config";
    public static final String FILE_CSV = "file-csv";
    public static final String FILE_DATA = "file-data";
    public static final String FILE_DISC_IMAGE = "file-disc-image";
    public static final String FILE_ERROR = "file-error";
    public static final String FILE_EXCEL = "file-excel";
    public static final String FILE_FLASH = "file-flash";
    public static final String FILE_FOOTER = "file-footer";
    public static final String FILE_HEADER = "file-header";
    public static final String FILE_HORIZONTAL = "file-horizontal";
    public static final String FILE_IMAGE = "file-image";
    public static final String FILE_MDB = "file-mdb";
    public static final String FILE_PDF = "file-pdf";
    public static final String FILE_PPT = "file-ppt";
    public static final String FILE_PRESENTATION = "file-presentation";
    public static final String FILE_PROGRAMMING = "file-programming";
    public static final String FILE_PSD = "file-psd";
    public static final String FILE_REPORT = "file-report";
    public static final String FILE_TXT = "file-txt";
    public static final String FILE_TYPESCRIPT = "file-typescript";
    public static final String FILE_VIDEO = "file-video";
    public static final String FILE_WORD = "file-word";
    public static final String FILE_ZIP = "file-zip";
    public static final String FILES_ERROR = "files-error";
    public static final String FILM = "film";
    public static final String FOLDER = "folder";
    public static final String FOLDER_ADD = "folder-add";
    public static final String FOLDER_MORE = "folder-more";
    public static final String FOLDER_OPEN = "folder-open";
    public static final String FOLDER_UP = "folder-up";
    public static final String GROUP_COLLECTION = "group-collection";
    public static final String GROUP_FOOTER_SECTION = "group-footer-section";
    public static final String GROUP_HEADER_SECTION = "group-header-section";
    public static final String GROUP_SECTION = "group-section";
    public static final String HTML5 = "html5";
    public static final String INHERITED = "inherited";
    public static final String JS = "js";
    public static final String LIST_ROMAN_LOWER = "list-roman-lower";
    public static final String LIST_ROMAN_UPPER = "list-roman-upper";
    public static final String PAGE_FOOTER_SECTION = "page-footer-section";
    public static final String PAGE_HEADER_SECTION = "page-header-section";
    public static final String PARAMETER_BOOLEAN = "parameter-boolean";
    public static final String PARAMETER_DATE_TIME = "parameter-date-time";
    public static final String PARAMETER_FLOAT = "parameter-float";
    public static final String PARAMETER_INTEGER = "parameter-integer";
    public static final String PARAMETER_STRING = "parameter-string";
    public static final String PARAMETERS = "parameters";
    public static final String PARAMETERS_BYTE_ARRAY = "parameters-byte-array";
    public static final String PARAMETERS_UNKNOWN = "parameters-unknown";
    public static final String PLAN = "plan";
    public static final String SLN = "sln";
    public static final String SUBREPORT = "subreport";
    public static final String TABLE_POSITION_CENTER = "table-position-center";
    public static final String TABLE_POSITION_END = "table-position-end";
    public static final String TABLE_POSITION_START = "table-position-start";
    public static final String TOC_SECTION = "toc-section";
    public static final String TOC_SECTION_LEVEL = "toc-section-level";
    public static final String VB = "vb";
    public static final String VBPROJ = "vbproj";
    public static final @Deprecated String ASCX = "ascx";
    public static final @Deprecated String BAC = "bac";

    // Images //
    public static final String BLUR = "blur";
    public static final String BRIGHTNESS_CONTRAST = "brightness-contrast";
    public static final String BRUSH = "brush";
    public static final String CAMERA = "camera";
    public static final String CROP = "crop";
    public static final String DROPLET = "droplet";
    public static final String DROPLET_SLIDER = "droplet-slider";
    public static final String FLIP_HORIZONTAL = "flip-horizontal";
    public static final String FLIP_VERTICAL = "flip-vertical";
    public static final String GRAYSCALE = "grayscale";
    public static final String IMAGE = "image";
    public static final String IMAGE_EXPORT = "image-export";
    public static final String IMAGE_RESIZE = "image-resize";
    public static final String IMAGES = "images";
    public static final String INVERT_COLORS = "invert-colors";
    public static final String MIRROR = "mirror";
    public static final String PALETTE = "palette";
    public static final String PHOTOS = "photos";
    public static final String ROTATE = "rotate";
    public static final String ROTATE_LEFT = "rotate-left";
    public static final String ROTATE_RIGHT = "rotate-right";
    public static final String ROUND_CORNERS = "round-corners";
    public static final String SHAPE_LINE = "shape-line";
    public static final String SHAPES = "shapes";
    public static final String SHARPEN = "sharpen";
    public static final String SLIDERS = "sliders";
    public static final String TRANSPARENCY = "transparency";
    public static final String ZOOM_ACTUAL_SIZE = "zoom-actual-size";
    public static final String ZOOM_BEST_FIT = "zoom-best-fit";
    public static final @Deprecated String ALIGN_BOTTOM_ELEMENT = "align-bottom-element";
    public static final @Deprecated String ALIGN_CENTER_ELEMENT = "align-center-element";
    public static final @Deprecated String ALIGN_LEFT_ELEMENT = "align-left-element";
    public static final @Deprecated String ALIGN_MIDDLE_ELEMENT = "align-middle-element";
    public static final @Deprecated String ALIGN_RIGHT_ELEMENT = "align-right-element";
    public static final @Deprecated String ALIGN_TOP_ELEMENT = "align-top-element";
    public static final @Deprecated String BACK_ELEMENT = "back-element";
    public static final @Deprecated String BACKGROUND = "background";
    public static final @Deprecated String BACKGROUND_REMOVE = "background-remove";
    public static final @Deprecated String BACKWARD_ELEMENT = "backward-element";
    public static final @Deprecated String FORWARD_ELEMENT = "forward-element";
    public static final @Deprecated String FRONT_ELEMENT = "front-element";
    public static final @Deprecated String FULL_SCREEN = "full-screen";
    public static final @Deprecated String FULL_SCREEN_EXIT = "full-screen-exit";
    public static final @Deprecated String GREYSCALE = "greyscale";
    public static final @Deprecated String LINE = "line";
    public static final @Deprecated String OPACITY = "opacity";
    public static final @Deprecated String PAINT = "paint";
    public static final @Deprecated String PAINT_REMOVE = "paint-remove";
    public static final @Deprecated String PHOTO = "photo";
    public static final @Deprecated String PHOTO_CAMERA = "photo-camera";
    public static final @Deprecated String PHOTO_EXPORT = "photo-export";
    public static final @Deprecated String RESET_COLOR = "reset-color";
    public static final @Deprecated String SATURATION = "saturation";
    public static final @Deprecated String SHAPE = "shape";

    // Layout //
    public static final String GRID = "grid";
    public static final String GRID_LAYOUT = "grid-layout";
    public static final String GROUP = "group";
    public static final String UNGROUP = "ungroup";
    public static final String HANDLE_DRAG = "handle-drag";
    public static final String LAYOUT = "layout";
    public static final String LAYOUT_1_BY_4 = "layout-1-by-4";
    public static final String LAYOUT_2_BY_2 = "layout-2-by-2";
    public static final String LAYOUT_SIDE_BY_SIDE = "layout-side-by-side";
    public static final String LAYOUT_STACKED = "layout-stacked";
    public static final String COLUMNS = "columns";
    public static final String ROWS = "rows";
    public static final String REORDER = "reorder";
    public static final String OVERLAP = "overlap";
    public static final String BOX_SIZING = "box-sizing";
    public static final String DISPLAY_BLOCK = "display-block";
    public static final String DISPLAY_FLEX = "display-flex";
    public static final String DISPLAY_INLINE_FLEX = "display-inline-flex";
    public static final String GAP_COLUMN = "gap-column";
    public static final String GAP_ROW = "gap-row";
    public static final String MAX_HEIGHT = "max-height";
    public static final String MAX_WIDTH = "max-width";
    public static final String MIN_HEIGHT = "min-height";
    public static final String MIN_WIDTH = "min-width";
    public static final String PADDING_BOTTOM = "padding-bottom";
    public static final String PADDING_LEFT = "padding-left";
    public static final String PADDING_RIGHT = "padding-right";
    public static final String PADDING_TOP = "padding-top";
    public static final String PADDING = "padding";
    public static final String DISPLAY_INLINE_BLOCK = "display-inline-block";
    public static final String HANDLE_DRAG_DOTS = "handle-drag-dots";

    // List //
    public static final String LIST_LATIN_BIG = "list-latin-big";
    public static final String LIST_LATIN_SMALL = "list-latin-small";
    public static final String LIST_ROMAN_BIG = "list-roman-big";
    public static final String LIST_ROMAN_SMALL = "list-roman-small";
    public static final String LIST_UNORDERED_OUTLINE = "list-unordered-outline";
    public static final String LIST_UNORDERED_SQUARE = "list-unordered-square";

    // Maps //
    public static final String LOCATIONS = "locations";
    public static final String GLOBE_OUTLINE = "globe-outline";
    public static final String GLOBE = "globe";
    public static final String MAP_MARKER = "map-marker";
    public static final String MAP_MARKER_TARGET = "map-marker-target";
    public static final String PIN = "pin";
    public static final String UNPIN = "unpin";
    public static final @Deprecated String MARKER_PIN = MAP_MARKER;
    public static final @Deprecated String MARKER_PIN_TARGET = MAP_MARKER_TARGET;

    // Media //
    public static final String CLOSED_CAPTIONS = "closed-captions";
    public static final String FORWARD = "forward";
    public static final String HD = "hd";
    public static final String MICROPHONE_OUTLINE = "microphone-outline";
    public static final String MICROPHONE_SOLID = "microphone-solid";
    public static final String MUSIC_NOTES = "music-notes";
    public static final String PAUSE = "pause";
    public static final String PAUSE_SM = "pause-sm";
    public static final String PLAY = "play";
    public static final String PLAY_SM = "play-sm";
    public static final String PLAYLIST = "playlist";
    public static final String REWIND = "rewind";
    public static final String STOP = "stop";
    public static final String STOP_SM = "stop-sm";
    public static final String VOLUME_DOWN = "volume-down";
    public static final String VOLUME_MUTE = "volume-mute";
    public static final String VOLUME_UP = "volume-up";
    public static final @Deprecated String AUDIO = MUSIC_NOTES;
    public static final @Deprecated String VOLUME_OFF = VOLUME_MUTE;
    public static final @Deprecated String SUBTITLES = CLOSED_CAPTIONS;

    // Misc //
    public static final String SPARKLES = "sparkles";
    public static final String WALLET_SOLID = "wallet-solid";
    public static final String VAN = "van";
    public static final String TRUCK = "truck";
    public static final String WALLET_OUTLINE = "wallet-outline";
    public static final String TRANSACTIONS = "transactions";
    public static final String RECYCLE_SOLID = "recycle-solid";
    public static final String INDUSTRIAL_VEHICLE = "industrial-vehicle";
    public static final String RECYCLE_OUTLINE = "recycle-outline";
    public static final String PLANE_SOLID = "plane-solid";
    public static final String PLANE_OUTLINE = "plane-outline";
    public static final String MONEY_EXCHANGE = "money-exchange";
    public static final String SUSTAINABILITY = "sustainability";
    public static final String SPEED = "speed";
    public static final String THERAPIST_OUTLINE = "therapist-outline";
    public static final String THERAPIST_SOLID = "therapist-solid";
    public static final String PATIENT_SOLID = "patient-solid";
    public static final String PATIENT_OUTLINE = "patient-outline";
    public static final String NURSE_SOLID = "nurse-solid";
    public static final String NURSE_OUTLINE = "nurse-outline";
    public static final String FOOD_SOLID = "food-solid";
    public static final String FOOD_OUTLINE = "food-outline";
    public static final String AWARD_NUMBER_OUTLINE = "award-number-outline";
    public static final String AWARD_NUMBER_SOLID = "award-number-solid";
    public static final String AWARD_STAR_OUTLINE = "award-star-outline";
    public static final String AWARD_STAR_SOLID = "award-star-solid";
    public static final String BANKNOTE_OUTLINE = "banknote-outline";
    public static final String BANKNOTE_SOLID = "banknote-solid";
    public static final String BATHTUBE_OUTLINE = "bathtube-outline";
    public static final String BATHTUBE_SOLID = "bathtube-solid";
    public static final String BED_OUTLINE = "bed-outline";
    public static final String BED_SOLID = "bed-solid";
    public static final String BUG_OUTLINE = "bug-outline";
    public static final String BUG_SOLID = "bug-solid";
    public static final String BUILDINGS_OUTLINE = "buildings-outline";
    public static final String BUILDINGS_SOLID = "buildings-solid";
    public static final String BICYCLE = "bicycle";
    public static final String BUS = "bus";
    public static final String CAR = "car";
    public static final String DASHBOARD_OUTLINE = "dashboard-outline";
    public static final String DASHBOARD_SOLID = "dashboard-solid";
    public static final String DECISION = "decision";
    public static final String DIRECTIONS = "directions";
    public static final String EDUCATION_OUTLINE = "education-outline";
    public static final String EDUCATION_SOLID = "education-solid";
    public static final String HEADSET = "headset";
    public static final String LUGGAGE_OUTLINE = "luggage-outline";
    public static final String LUGGAGE_SOLID = "luggage-solid";
    public static final String NON_STOP_OUTLINE = "non-stop-outline";
    public static final String NON_STOP_SOLID = "non-stop-solid";
    public static final String PILLS_OUTLINE = "pills-outline";
    public static final String PILLS_SOLID = "pills-solid";
    public static final String CLEAN_OUTLINE = "clean-outline";
    public static final String CLEAN_SOLID = "clean-solid";
    public static final String CONCRETE_TRUCK = "concrete-truck";
    public static final String DISCOUNT_OUTLINE = "discount-outline";
    public static final String DISCOUNT_SOLID = "discount-solid";
    public static final String DOCTOR_OUTLINE = "doctor-outline";
    public static final String DOCTOR_SOLID = "doctor-solid";
    public static final String LAB_TECHNICIAN_OUTLINE = "lab-technician-outline";
    public static final String LAB_TECHNICIAN_SOLID = "lab-technician-solid";
    public static final String SWEEPER_VEHICLE = "sweeper-vehicle";
    public static final String WEIGHT_SCALE_OUTLINE = "weight-scale-outline";
    public static final String WEIGHT_SCALE_SOLID = "weight-scale-solid";

    // Navigation //
    public static final String ARROW_OVERFLOW_DOWN = "arrow-overflow-down";
    public static final String ARROWS_NO_CHANGE = "arrows-no-change";
    public static final String CARET_ALT_DOWN = "caret-alt-down";
    public static final String CARET_ALT_EXPAND = "caret-alt-expand";
    public static final String CARET_ALT_LEFT = "caret-alt-left";
    public static final String CARET_ALT_RIGHT = "caret-alt-right";
    public static final String CARET_ALT_TO_BOTTOM = "caret-alt-to-bottom";
    public static final String CARET_ALT_TO_LEFT = "caret-alt-to-left";
    public static final String CARET_ALT_TO_RIGHT = "caret-alt-to-right";
    public static final String CARET_ALT_TO_TOP = "caret-alt-to-top";
    public static final String CARET_ALT_UP = "caret-alt-up";
    public static final String CARET_BL = "caret-bl";
    public static final String CARET_BR = "caret-br";
    public static final String CARET_DOUBLE_ALT_DOWN = "caret-double-alt-down";
    public static final String CARET_DOUBLE_ALT_LEFT = "caret-double-alt-left";
    public static final String CARET_DOUBLE_ALT_RIGHT = "caret-double-alt-right";
    public static final String CARET_DOUBLE_ALT_UP = "caret-double-alt-up";
    public static final String CARET_TL = "caret-tl";
    public static final String CARET_TR = "caret-tr";
    public static final String CATEGORIZE = "categorize";
    public static final String CHEVRON_DOWN = "chevron-down";
    public static final String CHEVRON_LEFT = "chevron-left";
    public static final String CHEVRON_RIGHT = "chevron-right";
    public static final String CHEVRON_UP = "chevron-up";
    public static final String DRAG_AND_DROP = "drag-and-drop";
    public static final String HOME = "home";
    public static final String MENU = "menu";
    public static final @Deprecated String ARROW_45_DOWN_LEFT = "arrow-45-down-left";
    public static final @Deprecated String ARROW_45_DOWN_RIGHT = "arrow-45-down-right";
    public static final @Deprecated String ARROW_45_UP_LEFT = "arrow-45-up-left";
    public static final @Deprecated String ARROW_45_UP_RIGHT = "arrow-45-up-right";
    public static final @Deprecated String ARROW_60_DOWN = "arrow-60-down";
    public static final @Deprecated String ARROW_60_LEFT = "arrow-60-left";
    public static final @Deprecated String ARROW_60_RIGHT = "arrow-60-right";
    public static final @Deprecated String ARROW_60_UP = "arrow-60-up";
    public static final @Deprecated String ARROW_CHEVRON_DOWN = "arrow-chevron-down";
    public static final @Deprecated String ARROW_CHEVRON_LEFT = "arrow-chevron-left";
    public static final @Deprecated String ARROW_CHEVRON_RIGHT = "arrow-chevron-right";
    public static final @Deprecated String ARROW_CHEVRON_UP = "arrow-chevron-up";
    public static final @Deprecated String ARROW_DOUBLE_60_DOWN = "arrow-double-60-down";
    public static final @Deprecated String ARROW_DOUBLE_60_LEFT = "arrow-double-60-left";
    public static final @Deprecated String ARROW_DOUBLE_60_RIGHT = "arrow-double-60-right";
    public static final @Deprecated String ARROW_DOUBLE_60_UP = "arrow-double-60-up";
    public static final @Deprecated String ARROW_DRILL = "arrow-drill";
    public static final @Deprecated String ARROW_END_DOWN = "arrow-end-down";
    public static final @Deprecated String ARROW_END_LEFT = "arrow-end-left";
    public static final @Deprecated String ARROW_END_RIGHT = "arrow-end-right";
    public static final @Deprecated String ARROW_END_UP = "arrow-end-up";
    public static final @Deprecated String ARROW_PARENT = "arrow-parent";
    public static final @Deprecated String ARROW_ROOT = "arrow-root";
    public static final @Deprecated String ARROW_SEEK_DOWN = "arrow-seek-down";
    public static final @Deprecated String ARROW_SEEK_RIGHT = "arrow-seek-right";
    public static final @Deprecated String ARROW_SEEK_UP = "arrow-seek-up";
    public static final @Deprecated String ARROWS_DIMENSIONS = "arrows-dimensions";
    public static final @Deprecated String ARROWS_KPI = "arrows-kpi";
    public static final @Deprecated String ARROWS_RESIZING = "arrows-resizing";
    public static final @Deprecated String COLLAPSE_NE = "collapse-ne";
    public static final @Deprecated String COLLAPSE_NW = "collapse-nw";
    public static final @Deprecated String COLLAPSE_SE = "collapse-se";
    public static final @Deprecated String COLLAPSE_SW = "collapse-sw";
    public static final @Deprecated String KPI = "kpi";
    public static final @Deprecated String MORE_HORIZONTAL = "more-horizontal";
    public static final @Deprecated String MORE_VERTICAL = "more-vertical";
    public static final @Deprecated String RESIZE_NE = "resize-ne";
    public static final @Deprecated String RESIZE_NEW = "resize-new";
    public static final @Deprecated String RESIZE_SE = "resize-se";
    public static final @Deprecated String RESIZE_SW = "resize-sw";

    // Notifications //
    public static final String BELL = "bell";
    public static final String EXCLAMATION_CIRCLE = "exclamation-circle";
    public static final String INFO_CIRCLE = "info-circle";
    public static final String INFO_SOLID = "info-solid";
    public static final String QUESTION_CIRCLE = "question-circle";
    public static final String QUESTION_SOLID = "question-solid";
    public static final String WARNING_CIRCLE = "warning-circle";
    public static final String WARNING_TRIANGLE = "warning-triangle";
    public static final @Deprecated String ERROR = EXCLAMATION_CIRCLE;
    public static final @Deprecated String EXCEPTION = EXCLAMATION_CIRCLE;
    public static final @Deprecated String HELP = QUESTION_CIRCLE;
    public static final @Deprecated String INFO = INFO_SOLID;
    public static final @Deprecated String INFORMATION = INFO_CIRCLE;
    public static final @Deprecated String NOTIFICATION = INFO_CIRCLE;
    public static final @Deprecated String QUESTION = QUESTION_CIRCLE;
    public static final @Deprecated String WARNING = WARNING_TRIANGLE;

    // Social //
    public static final String BEHANCE = "behance";
    public static final String BEHANCE_BOX = "behance-box";
    public static final String BLOGGER = "blogger";
    public static final String BLOGGER_BOX = "blogger-box";
    public static final String DELICIOUS = "delicious";
    public static final String DELICIOUS_BOX = "delicious-box";
    public static final String DEVICES_OUTLINE = "devices-outline";
    public static final String DEVICES_SOLID = "devices-solid";
    public static final String DIGG = "digg";
    public static final String DIGG_BOX = "digg-box";
    public static final String DRIBBBLE = "dribbble";
    public static final String DRIBBBLE_BOX = "dribbble-box";
    public static final String ENVELOP = "envelop";
    public static final String ENVELOP_BOX = "envelop-box";
    public static final String ENVELOPE = "envelope";
    public static final String ENVELOPE_BOX = "envelope-box";
    public static final String FACEBOOK = "facebook";
    public static final String FACEBOOK_BOX = "facebook-box";
    public static final String GOOGLE = "google";
    public static final String GOOGLE_BOX = "google-box";
    public static final String GOOGLE_PLUS = "google-plus";
    public static final String GOOGLE_PLUS_BOX = "google-plus-box";
    public static final String INBOX = "inbox";
    public static final String INSTAGRAM = "instagram";
    public static final String INSTAGRAM_BOX = "instagram-box";
    public static final String LAPTOP_OUTLINE = "laptop-outline";
    public static final String LAPTOP_SOLID = "laptop-solid";
    public static final String LINKEDIN = "linkedin";
    public static final String LINKEDIN_BOX = "linkedin-box";
    public static final String MOBILE_OUTLINE = "mobile-outline";
    public static final String MOBILE_OUTLINE_RINGING = "mobile-outline-ringing";
    public static final String MOBILE_SOLID = "mobile-solid";
    public static final String MOBILE_SOLID_RINGING = "mobile-solid-ringing";
    public static final String MYSPACE = "myspace";
    public static final String MYSPACE_BOX = "myspace-box";
    public static final String PINTEREST = "pinterest";
    public static final String PINTEREST_BOX = "pinterest-box";
    public static final String REDDIT = "reddit";
    public static final String REDDIT_BOX = "reddit-box";
    public static final String RSS = "rss";
    public static final String RSS_BOX = "rss-box";
    public static final String SHARE = "share";
    public static final String SMS_OUTLINE = "sms-outline";
    public static final String SMS_SOLID = "sms-solid";
    public static final String STUMBLE_UPON = "stumble-upon";
    public static final String STUMBLE_UPON_BOX = "stumble-upon-box";
    public static final String TABLET_OUTLINE = "tablet-outline";
    public static final String TABLET_SOLID = "tablet-solid";
    public static final String TELL_A_FRIEND = "tell-a-friend";
    public static final String TELL_A_FRIEND_BOX = "tell-a-friend-box";
    public static final String TUMBLR = "tumblr";
    public static final String TUMBLR_BOX = "tumblr-box";
    public static final String TWITTER = "twitter";
    public static final String TWITTER_BOX = "twitter-box";
    public static final String USER = "user";
    public static final String USER_OUTLINE = "user-outline";
    public static final String USERS_OUTLINE = "users-outline";
    public static final String USERS_SOLID = "users-solid";
    public static final String VIMEO = "vimeo";
    public static final String VIMEO_BOX = "vimeo-box";
    public static final String WHATSAPP = "whatsapp";
    public static final String WHATSAPP_BOX = "whatsapp-box";
    public static final String X_LOGO = "x-logo";
    public static final String X_LOGO_BOX = "x-logo-box";
    public static final String YAMMER = "yammer";
    public static final String YAMMER_BOX = "yammer-box";
    public static final String YOUTUBE = "youtube";
    public static final String YOUTUBE_BOX = "youtube-box";
    public static final @Deprecated String EMAIL = ENVELOPE;
    public static final @Deprecated String EMAIL_BOX = ENVELOPE_BOX;
    public static final @Deprecated String LETTER = ENVELOPE;
    public static final @Deprecated String LETTER_BOX = ENVELOPE_BOX;

    // Text Formatting //
    public static final String ALIGN_BOTTOM = "align-bottom";
    public static final String ALIGN_CENTER = "align-center";
    public static final String ALIGN_JUSTIFY = "align-justify";
    public static final String ALIGN_LEFT = "align-left";
    public static final String ALIGN_MIDDLE = "align-middle";
    public static final String ALIGN_REMOVE = "align-remove";
    public static final String ALIGN_RIGHT = "align-right";
    public static final String ALIGN_TOP = "align-top";
    public static final String ALL = "all";
    public static final String BOLD = "bold";
    public static final String BORDER_BOTTOM = "border-bottom";
    public static final String BORDER_LEFT = "border-left";
    public static final String BORDER_RIGHT = "border-right";
    public static final String BORDER_TOP = "border-top";
    public static final String BORDERS_ALL = "borders-all";
    public static final String BORDERS_INSIDE = "borders-inside";
    public static final String BORDERS_INSIDE_HORIZONTAL = "borders-inside-horizontal";
    public static final String BORDERS_INSIDE_VERTICAL = "borders-inside-vertical";
    public static final String BORDERS_NONE = "borders-none";
    public static final String BORDERS_OUTSIDE = "borders-outside";
    public static final String BORDERS_SHOW_HIDE = "borders-show-hide";
    public static final String CONVERT_LOWERCASE = "convert-lowercase";
    public static final String CONVERT_UPPERCASE = "convert-uppercase";
    public static final String DIV = "div";
    public static final String FONT_FAMILY = "font-family";
    public static final String FONT_GROW = "font-grow";
    public static final String FONT_SHRINK = "font-shrink";
    public static final String FONT_SIZE = "font-size";
    public static final String FOREGROUND_COLOR = "foreground-color";
    public static final String H1 = "h1";
    public static final String H2 = "h2";
    public static final String H3 = "h3";
    public static final String H4 = "h4";
    public static final String H5 = "h5";
    public static final String H6 = "h6";
    public static final String HORIZONTAL_RULE = "horizontal-rule";
    public static final String INDENT = "indent";
    public static final String INSERT_BOTTOM = "insert-bottom";
    public static final String INSERT_MIDDLE = "insert-middle";
    public static final String INSERT_TOP = "insert-top";
    public static final String ITALIC = "italic";
    public static final String LETTER_SPACE = "letter-space";
    public static final String LINE_HEIGHT = "line-height";
    public static final String LIST_ORDERED = "list-ordered";
    public static final String LIST_UNORDERED = "list-unordered";
    public static final String OUTDENT = "outdent";
    public static final String PARAGRAPH_HEIGHT = "paragraph-height";
    public static final String REGULAR_EXPRESSION = "regular-expression";
    public static final String REPLACE_ALL = "replace-all";
    public static final String REPLACE_SINGLE = "replace-single";
    public static final String REPORT_ELEMENT = "report-element";
    public static final String RIGHT_DOUBLE_QUOTES = "right-double-quotes";
    public static final String STRIKETHROUGH = "strikethrough";
    public static final String SUB_SCRIPT = "sub-script";
    public static final String SUP_SCRIPT = "sup-script";
    public static final String TABLE_ALIGN_BOTTOM_CENTER = "table-align-bottom-center";
    public static final String TABLE_ALIGN_BOTTOM_LEFT = "table-align-bottom-left";
    public static final String TABLE_ALIGN_BOTTOM_RIGHT = "table-align-bottom-right";
    public static final String TABLE_ALIGN_MIDDLE_CENTER = "table-align-middle-center";
    public static final String TABLE_ALIGN_MIDDLE_LEFT = "table-align-middle-left";
    public static final String TABLE_ALIGN_MIDDLE_RIGHT = "table-align-middle-right";
    public static final String TABLE_ALIGN_REMOVE = "table-align-remove";
    public static final String TABLE_ALIGN_TOP_CENTER = "table-align-top-center";
    public static final String TABLE_ALIGN_TOP_LEFT = "table-align-top-left";
    public static final String TABLE_ALIGN_TOP_RIGHT = "table-align-top-right";
    public static final String TEXT_CLIP = "text-clip";
    public static final String TEXT_OVERFLOW = "text-overflow";
    public static final String TEXT_TRUNCATE = "text-truncate";
    public static final String TEXT_WRAP = "text-wrap";
    public static final String TEXT_WRAP_ARROW = "text-wrap-arrow";
    public static final String UNDERLINE = "underline";
    public static final String WHOLE_WORD = "whole-word";
    public static final @Deprecated String BORDER = BORDERS_ALL;
    public static final @Deprecated String BORDER_NO = BORDERS_NONE;

    // Toggle //
    public static final String BOOKMARK = "bookmark";
    public static final String BOOKMARK_OUTLINE = "bookmark-outline";
    public static final String CHECKBOX = "checkbox";
    public static final String CHECKBOX_CHECKED = "checkbox-checked";
    public static final String CHECKBOX_INDETERMINATE = "checkbox-indeterminate";
    public static final String CHECKBOX_NULL = "checkbox-null";
    public static final String CIRCLE = "circle";
    public static final String HEART = "heart";
    public static final String HEART_OUTLINE = "heart-outline";
    public static final String RADIOBUTTON = "radiobutton";
    public static final String RADIOBUTTON_CHECKED = "radiobutton-checked";
    public static final String STAR = "star";
    public static final String STAR_OUTLINE = "star-outline";
    public static final String THUMB_DOWN = "thumb-down";
    public static final String THUMB_DOWN_OUTLINE = "thumb-down-outline";
    public static final String THUMB_UP = "thumb-up";
    public static final String THUMB_UP_OUTLINE = "thumb-up-outline";
    public static final @Deprecated String FAV = HEART;
    public static final @Deprecated String FAV_OUTLINE = HEART_OUTLINE;
    public static final @Deprecated String FAVORITE = HEART;
    public static final @Deprecated String FAVORITE_OUTLINE = HEART_OUTLINE;
    public static final @Deprecated String SHAPE_CIRCLE = CIRCLE;
    public static final @Deprecated String SHAPE_RECT = CHECKBOX;
    public static final @Deprecated String TRI_STATE_INDETERMINATE = CHECKBOX_INDETERMINATE;
    public static final @Deprecated String TRI_STATE_NULL = CHECKBOX_NULL;

    /**
     * Constants class
     */
    private KendoIcon()
    {
    }

    /**
     * Indicates whether the icon is {@link KendoIcon#NONE}
     *
     * @param icon
     *            the icon
     * @return true or false
     */
    public static boolean isNone(String icon)
    {
        return KendoIcon.NONE.equals(icon);
    }

    /**
     * Gets the full css-class of the icon
     *
     * @param icon
     *            the {@link KendoIcon}
     * @return the full css-class
     */
    public static String getCssClass(String icon)
    {
        if (!isNone(icon)) {
            return String.format("%s k-i-%s", K_ICON, icon);
        }

        return "";
    }
}
