/**
 *  Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  See the NOTICE file distributed with
 *  this work for additional information regarding copyright ownership.
 *  The ASF licenses this file to You under the Apache License, Version 2.0
 *  (the "License"); you may not use this file except in compliance with
 *  the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.wicketstuff.stateless.components;

import static org.wicketstuff.stateless.StatelessEncoder.mergeParameters;

import org.apache.wicket.markup.html.link.Link;
import org.apache.wicket.model.IModel;
import org.apache.wicket.request.Url;
import org.apache.wicket.request.mapper.parameter.PageParameters;

/**
 * @author jfk
 * 
 */
public abstract class StatelessLink<T> extends Link<T>
{
    private static final long serialVersionUID = 397549666360107292L;
    
    private final PageParameters parameters;

    public StatelessLink(final String id)
    {
        this(id, null, null);
    }

    public StatelessLink(final String id, final IModel<T> model)
    {
        this(id, model, null);
    }

    public StatelessLink(final String id, final IModel<T> model, final PageParameters params)
    {
        super(id, model);
        
        setMarkupId(id);

        this.parameters = params;
    }

    protected final PageParameters getPageParameters()
    {
        return parameters;
    }

    /**
     * Hints that this component is stateless.
     * 
     * @return always {@literal true}
     * @see Link#getStatelessHint()
     */
    @Override
    protected boolean getStatelessHint()
    {
        return true;
    }

    /**
     * Adds the parameters to the {@link CharSequence} generated by the
     * superclass.
     * 
     * @see Link#getURL()
     */
    @Override
    protected CharSequence getURL()
    {
        final Url url = Url.parse(super.getURL().toString());

        Url mergedUrl = mergeParameters(url, parameters);
        return mergedUrl.toString();
    }
}
