grant
{
	permission org.wicketstuff.security.hive.authorization.TestPermission "A", "inherit, render";
	permission org.wicketstuff.security.hive.authorization.TestPermission "A", "enable";
};
grant principal org.wicketstuff.security.hive.authorization.SimplePrincipal "test1"
{
	permission org.wicketstuff.security.hive.authorization.TestPermission "1.A", "inherit, render";
	permission org.wicketstuff.security.hive.authorization.TestPermission "1.A", "enable";
};
grant principal org.wicketstuff.security.hive.authorization.SimplePrincipal "test2"
{
	permission org.wicketstuff.security.hive.authorization.TestPermission "2.A", "inherit, render";
	permission org.wicketstuff.security.hive.authorization.TestPermission "2.A", "enable";
	{
	permission org.wicketstuff.security.hive.authorization.TestPermission "2.B", "inherit, render, enable";
	permission org.wicketstuff.security.hive.authorization.TestPermission "2.B", "enable";
	permission org.wicketstuff.security.hive.authorization.TestPermission "2.C", "render, enable";
	permission org.wicketstuff.security.hive.authorization.TestPermission "2.C.1", "enable";
	};
};
grant principal org.wicketstuff.security.hive.authorization.SimplePrincipal "test3"
{
};
grant principal org.wicketstuff.security.hive.authorization.SimplePrincipal "test4"
{};

grant principal org.wicketstuff.security.hive.authorization.SimplePrincipal "test5"
};
grant principal org.wicketstuff.security.hive.authorization.SimplePrincipal "test6"
{
	permission org.wicketstuff.security.hive.authorization.TestPermission "6.A", "inherit, render";
	permission org.wicketstuff.security.hive.authorization.TestPermission "6.A", "enable";
	permission org.wicketstuff.security.hive.authorization.TestPermission "6.B", "inherit, render, enable";
	permission org.wicketstuff.security.hive.authorization.TestPermission "6.B", "enable";
	grant principal org.wicketstuff.security.hive.authorization.SimplePrincipal "test7"
	{
		permission org.wicketstuff.security.hive.authorization.TestPermission "7.A", "inherit, render";
		permission org.wicketstuff.security.hive.authorization.TestPermission "7.A", "enable";
		permission org.wicketstuff.security.hive.authorization.TestPermission "7.B", "inherit, render, enable";
		permission org.wicketstuff.security.hive.authorization.TestPermission "7.B", "enable";
		permission org.wicketstuff.security.hive.authorization.TestPermission "7.C", "render, enable";
		permission org.wicketstuff.security.hive.authorization.TestPermission "7.C.1", "enable";
	};
	permission org.wicketstuff.security.hive.authorization.TestPermission "6.C", "render, enable";
	permission org.wicketstuff.security.hive.authorization.TestPermission "6.C.1", "enable";
};
grant principal org.wicketstuff.security.hive.authorization.SimplePrincipal "test8"
{
	permission org.wicketstuff.security.hive.authorization.TestPermission "8.A";
	permission org.wicketstuff.security.hive.authorization.TestPermission "8.B";
	permission org.wicketstuff.security.hive.authorization.PestTermission "8.C";
	permission org.wicketstuff.security.hive.authorization.FaultyPermission "8.D";
};
grant principal ${auth}.SimplePrincipal "${test}${nine}"
{
	permission ${perm} "${nine}.A";
	permission ${perm} "${nine}.B", "test";
};
grant principal org.wicketstuff.security.hive.authorization.SimplePrincipal "test9B"
{
	permission org.wicketstuff.security.hive.authorization.TestPermission "${test}.ContainerPage2:${test}.ContainerPage2$SecureMarkupContainer", "inherit, render";
	permission org.wicketstuff.security.hive.authorization.TestPermission "test2.ContainerPage2:${test}.ContainerPage2$SecureMarkupContainer", "inherit, render";
};
grant principal org.wicketstuff.security.hive.authorization.SimplePrincipal "test10"
	permission org.wicketstuff.security.hive.authorization.TestPermission "10.A";
{
	permission org.wicketstuff.security.hive.authorization.TestPermission "10.B";