tinyMCE.addI18n('da.fullpage_dlg',{
title:"Dokument egenskaber",
meta_tab:"Generelt",
appearance_tab:"Udseende",
advanced_tab:"Advanceret",
meta_props:"Meta information",
langprops:"Sprog og kodning",
meta_title:"Titel",
meta_keywords:"N\u00F8gleord",
meta_description:"Beskrivelse",
meta_robots:"Robots",
doctypes:"Doctype",
langcode:"Sprogkode",
langdir:"Sprogretning",
ltr:"Venstre mod h\u00F8jre",
rtl:"H\u00F8jre md venstre",
xml_pi:"XML declaration",
encoding:"Tegns\u00E6t",
appearance_bgprops:"Baggrundsegenskaber",
appearance_marginprops:"Body margins",
appearance_linkprops:"Link farver",
appearance_textprops:"Tekstegenskaber",
bgcolor:"Baggrundsfarve",
bgimage:"Baggrundsbillede",
left_margin:"Venstre margin",
right_margin:"H\u00F8jre margin",
top_margin:"Top margin",
bottom_margin:"Bund margin",
text_color:"Tekstfarve",
font_size:"Skriftst\u00F8rrelse",
font_face:"Skrifttype",
link_color:"Linkfarve",
hover_color:"Farve ved aktivering",
visited_color:"Farve efter museklik",
active_color:"Farve ved museklik",
textcolor:"Farve",
fontsize:"Skriftst\u00F8rrelse",
fontface:"Skrifttype",
meta_index_follow:"Indeks og f\u00F8lg links",
meta_index_nofollow:"Indeks og f\u00F8lg ikke links",
meta_noindex_follow:"Ingen indeks, men f\u00F8lg links",
meta_noindex_nofollow:"Ingen indeks og f\u00F8lg ikke links",
appearance_style:"Stylesheet and style egenskaber",
stylesheet:"Stylesheet",
style:"Style",
author:"Forfatter",
copyright:"Copyright",
add:"Tilf\u00F8j nyt element",
remove:"Slet valgte element",
moveup:"Flyt valgte element op",
movedown:"Flyt valgte element ned",
head_elements:"Hovedelement",
info:"Information",
add_title:"Titelelement",
add_meta:"Metaelement",
add_script:"Scriptelement",
add_style:"Styleelement",
add_link:"Linkelement",
add_base:"Baseelement",
add_comment:"Kommentar node",
title_element:"Titelelement",
script_element:"Scriptelement",
style_element:"Styleelement",
base_element:"Baseelement",
link_element:"Linkelement",
meta_element:"Metaelement",
comment_element:"Kommentar",
src:"Src",
language:"Sprog",
href:"Href",
target:"Destination",
type:"Type",
charset:"Tegns\u00E6t",
defer:"Defer",
media:"Media",
properties:"Egenskaber",
name:"Navn",
value:"V\u00E6rdi",
content:"Indhold",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"Generelt",
advanced_props:"Advanceret"
});