grant principal ${SimplePrincipal} "basic"
{
	permission ${ComponentPermission} "${myPackage}.MockHomePage", "inherit, render";
	permission ${ComponentPermission} "${myPackage}.MockHomePage", "enable";
	permission ${ComponentPermission} "${myPackage}.PageA", "render";
	permission ${ComponentPermission} "${myPackage}.PageA", "enable";
	permission ${ComponentPermission} "${myPackage}.PageA:readonly", "render";
};
grant principal ${SimplePrincipal} "admin"
{
	permission ${ComponentPermission} "${myPackage}.VerySecurePage", "inherit, render";
	permission ${ComponentPermission} "${myPackage}.VerySecurePage", "enable";
};
grant principal ${SimplePrincipal} "all permissions"
{
	permission ${AllPermissions} "everything";
};
grant principal ${SimplePrincipal} "container1"
{
	//everything should be rendered
	permission ${ComponentPermission} "${myPackage}.ContainerHomePage", "inherit, render";
	permission ${ComponentPermission} "${myPackage}.ContainerHomePage", "enable";
};
grant principal ${SimplePrincipal} "container2"
{
	//everything starting from lvl1 should be rendered
	permission ${ComponentPermission} "${myPackage}.ContainerHomePage", "render";
	permission ${ComponentPermission} "${myPackage}.ContainerHomePage", "enable";
	permission ${ComponentPermission} "org.wicketstuff.security.components.L1Container", "inherit, render";
	
};
grant principal ${SimplePrincipal} "container3"
{
	//everything starting from lvl2 should be rendered
	permission ${ComponentPermission} "${myPackage}.ContainerHomePage", "render";
	permission ${ComponentPermission} "${myPackage}.ContainerHomePage", "enable";
	permission ${ComponentPermission} "org.wicketstuff.security.components.L1Container", "render";
	//this would work too but then we would grant permission for every WebMarkupContainer
	//permission ${ComponentPermission} "org.apache.wicket.markup.html.WebMarkupContainer", "inherit, render";
	//better would be to add the parent hierarchy too
	permission ${ComponentPermission} "org.wicketstuff.security.components.L1Container:org.apache.wicket.markup.html.WebMarkupContainer", "inherit, render";
	//or 
	//permission ${ComponentPermission} "${myPackage}.ContainerHomePage:org.wicketstuff.security.components.L1Container:org.apache.wicket.markup.html.WebMarkupContainer", "inherit, render";
	
};
grant principal ${SimplePrincipal} "container4"
{
	permission ${ComponentPermission} "${myPackage}.ContainerPage2", "render";
	permission ${ComponentPermission} "${myPackage}.ContainerPage2", "enable";
};
grant principal ${SimplePrincipal} "container5"
{
	permission ${ComponentPermission} "${myPackage}.ContainerPage2:secure", "inherit, render";
	permission ${ComponentPermission} "${myPackage}.ContainerPage2", "enable";
};
grant principal ${SimplePrincipal} "container6"
{
	permission ${ComponentPermission} "${myPackage}.ContainerPage2:${myPackage}.ContainerPage2$SecureMarkupContainer", "inherit, render";
	permission ${ComponentPermission} "${myPackage}.ContainerPage2", "enable";
};
grant principal ${SimplePrincipal} "container7"
{
	permission ${ComponentPermission} "${myPackage}.ContainerPage2$SecureMarkupContainer", "inherit, render";
	permission ${ComponentPermission} "${myPackage}.ContainerPage2", "enable";
};
